export const SET_USERS = 'SET_USERS'
export const ADD_USER = 'ADD_USER'
export const FORMAT_USERS = 'FORMAT_USER'
export const SORT_USERS = 'SORT_USERS'
export const SET_POSITION = 'SET_POSITION'
export const CHANGE_POSITION = 'CHANGE_POSITION'
export const CHANGE_USER = 'CHANGE_USER'